services:
  - type: web
    name: magical-tic-tac-toe
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
    plan: free